In [6]:
import numpy as np

In [7]:
#generate a q-ary lattice and it's basis
def Matrix_Basis(n,m_1,q):
    """
    Input: 
    n: The number of rows of output matrix A
    m_1: The number of columns of output matrix A
    q: A prime number
    *Output: A couple includes
    A: An nxm_1 matrix 
    T_A: Basis (as matrix) of perp. q-ary lattice corresponding to A
    """
    #m_2=l*m_1
    A=matrix(GF(q),np.random.randint(q,size=(n,m_1)))
    C=matrix(ZZ,np.identity(m_1, dtype= int))
    
    #hermite normal form basis function.
    def q_arybasis(A,q):
        T_A=matrix(ZZ,((A).right_kernel()).basis())
        for i in range(n):
            T_A= matrix(ZZ,np.concatenate((T_A,matrix(q*matrix(np.identity(m_1,dtype=int))[m_1-n+i])), axis= 0))
        T_A=T_A.T
        return T_A
    T_A=q_arybasis(A,q)
    return(A,T_A)
#=====================================================================
def ExtBasis(A,M,T_A):
    """
    *Input:
    A: An nxm matrix in Z_q
    T_A: Basis of perp. q-ary lattice corresponding to A
    M: An arbitrary matrix
    *Output: A couple
    A_1= [A|M]
    T_A1: Basis for perp. q-ary lattice corresponding to A_1
    """
    W=matrix(ZZ,A.solve_right(-M))
    T_A1=matrix(ZZ,(T_A.augment(W)).stack(zero_matrix(ZZ,m_2,m_1).augment(identity_matrix(ZZ,m_2))))
    A_1=matrix(GF(q),A.augment(M))
    return A_1, T_A1

#=======================================================================
#A TEST CASE 
#r=2
n=5
q= 79 #next_prime(2^10)
m_1=20 #int(2*n*log(q,2))
m_2=10

A,T_A=Matrix_Basis(n,m_1,q)
M=matrix(GF(q),np.random.randint(q,size=(n,m_2)))

A_1,T_A1=ExtBasis(A,M,T_A)
#l= int(log(q,r))
#d=int(2*n*log(q,2))


In [8]:
print(A*T_A)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [9]:
A_1*T_A1

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]