In [4]:
#ToBasis Al. is constructed in MG02 and mentioned in CHKP10, lemma 2.1 and ABB10 lemma 3
import numpy as np

In [5]:
def Matrix_Basis(n,m_1,q):   
#generate a q-ary lattice and it's basis in lower triangle matrix form
    """
    Input: 
    n: The number of rows of output matrix A
    m_1: The number of columns of output matrix A
    q: A prime number
    *Output: A couple includes
    A: An nxm_1 integer matrix 
    T_A: Basis (as matrix) of perp. q-ary lattice corresponding to A
    """
    #m_2=l*m_1
    A=matrix(GF(q),np.random.randint(q,size=(n,m_1)))
    C=matrix(ZZ,np.identity(m_1, dtype= int))
    #hermite normal form basis function.
    def q_arybasis(A,q):
        H=matrix(ZZ,((A).right_kernel()).basis())
        for i in range(n):
            H= matrix(ZZ,np.concatenate((H,matrix(q*C[m_1-n+i])), axis= 0))
        H=H.T
        return H
    T_A=q_arybasis(A,q)
    return(A,T_A)
#=============================================================

def independent_vector(S): 
#generate random and linearly independent vectors from basis S of a lattice
    """
    *Input: 
    S: Basis of lattice
    *Output:
    A matrix B whose rows are independent vectors in lattice which has Basis S
    """
    m_1=S.rank()
    B=matrix(S*vector(matrix(ZZ,np.random.randint(q,size=(m_1,1))))).T #first vector of B
    size_B=1
    while size_B < m_1:
        A = vector(matrix(ZZ,np.random.randint(q,size=(m_1,1))))
        A = matrix(S*A).T
        if B.rank()==m_1:
            break
        h=(B.T).rank()
        if ((B.augment(A)).T).rank()==h+1:
            B=B.augment(A) 
            size_B=size_B+1
    return(B)
# ===========================================================
def ToBasis(V,S):
    """
    *Input:
    V: Independent short lattice vectors
    S: A basis of lattice L
    *Output: 
    A new short basis S_1 of lattice L
    """
    Q=matrix(ZZ,(S**(-1))*V)
    T = Q.echelon_form()
    U= Q*(T**(-1))
    S_1=matrix(ZZ,S*U)
    return(S_1,U)
#===================================================================
# A TEST CASE
#r=2
n=5
q= 79 #next_prime(2^10)
    #def GenTrap(n,q,r):
m_1=20 #int(2*n*log(q,2))
#l= int(log(q,r))
#d=int(2*n*log(q,2))
A_1,S=Matrix_Basis(n,m_1,q)
V=independent_vector(S)

#====================================

S_1,U=ToBasis(V,S)

In [6]:
Q=S**(-1)*V
print(Q)

[51 66 16 13  2 60 71  0 46 74 39 29  2 14 29  5 42 17 35 40]
[19 16  9  4 48 78 27 36 21 30  3 71 58 76 43 75 29 50 23 76]
[ 5  6  0 65 68 17 15 59 26 77  6 72 30 60 51 52 36 12 34  7]
[ 7 52 35 77 39 38 78  4 75 27 69 38 16 73 30 23 13 26 33 18]
[ 8 36 31 54 33  5 75 77 18  9 18  0  7  0  0 12  3 56 16 57]
[ 4 16 39 26 41 57  1 65  1 75 38 14 47  9  9 55  9 31 31 39]
[72  9 72 76 33 12 38 16 74 58 23  2 15 76 28 40 21 53  7 70]
[11 43 69 23 43 47 47 60 12 24 48 66 70 13 70 13 18 18 76  1]
[49  7  3 23 19  4  1 43  1  4 18 44 68 58 29 21 75  7 49 20]
[76 27 23 27 21 50 23  0 10 74 62 46 43 45 71 14 39 76  1 72]
[22 57  8 50 11  0 15  0 45 44 28 27 40  7 41 23 73 34 59  9]
[45 25 46 50 65 62 41 27 13 23  2 73 43 57 28 14 20 23  4 46]
[77  7 76 48 46  7 33 33  0 59 36  9 57 52 35 72 44  9 56 78]
[ 6 46 13 52 76 64 63 24 69 28 71 42 32 46 21 60 32  8 61  6]
[78 73 53 58 75 67 24  1 71  8 73 44 41 70 58  7 63 39 59 47]
[34  9 61 64 57  5 29 66 34 71 54 48 68 61 35 41 40 24  9 26]
[45 46 3

In [7]:
#Check if S is basis of labda_perp(A_1)
A_1*S

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [9]:
#Check if S_1 is basis of labda_perp(A_1)
print(det(S_1^(-1)*S))
A_1*S_1

-1


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [10]:
#check if U is unimodular matrix
U.det()


-1

In [9]:
print(S_1)

[     51      66      16      13       2      60      71       0      46      74      39      29       2      14      29       5      42      17    -155    -337]
[     19      16       9       4      48      78      27      36      21      30       3      71      58      76      43      75      29      50    -185    -320]
[      5       6       0      65      68      17      15      59      26      77       6      72      30      60      51      52      36      12    -188    -340]
[      7      52      35      77      39      38      78       4      75      27      69      38      16      73      30      23      13      26    -206    -389]
[      8      36      31      54      33       5      75      77      18       9      18       0       7       0       0      12       3      56    -147    -205]
[      4      16      39      26      41      57       1      65       1      75      38      14      47       9       9      55       9      31    -139    -236]
[     72       9      72    